#!/bin/bash

#For xtrace / debugging
#set -x


# if [ "$#" -ne 1 ]; then
#     usage
#     exit
# fi

outfile='readme.md'

# Add preamble for the readme
cat << INTRO > ${outfile}

# Readme

This repository contains quite useful resources on the following topics. 
Its in constant update, feel free to **Star** or **Watch** this repository, so that you get update notification as and when we update.

You may fork this repo and you can add your own awesome tools, techs that you find useful, and you can submit pull request

INTRO

# adding the content of banner to make readme nice
cat banner.txt >> $outfile


cat contributing-guide.md >> $outfile




while read -r line
do
    # Extract the first line of each file.
    fileheading=$(head -n 1 $line)
    
    # Remove the leading pound symbol
    fileheading="${fileheading:1}"
    

    echo "* [$fileheading]($line)" >> ${outfile}
done < <(ls *.md)

# Add credit 
cat << EOFFF >> ${outfile}

#### Note

This file was auto generated by **Table of content generator** [create-toc.sh](create-toc.sh)

EOFFF